{% set name = "xhtml2pdf" %}
{% set version = "0.2.6" %}
{% set sha256 = "1cb72782ac5fb67b9fcab20a37a65c6d61afde4cfd5a090ff5ba6d737c589a97" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pisa = xhtml2pdf.pisa:command
    - xhtml2pdf = xhtml2pdf.pisa:command
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - arabic_reshaper
    - html5lib >=1.0
    - pillow
    - pypdf2
    - python-bidi
    - reportlab >=3.0
    - six

test:
  imports:
    - xhtml2pdf
    - xhtml2pdf.config
    - xhtml2pdf.w3c
  commands:
    - pisa --help
    - xhtml2pdf --help

about:
  home: http://github.com/xhtml2pdf/xhtml2pdf
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: PDF generator using HTML and CSS

extra:
  recipe-maintainers:
    - mrakitin
