travis:
  secure:
    BINSTAR_TOKEN: JqJ3jPds3d1uYAqXVo1VhBD/mA4WqrWVUo4kFNkL/tgR3+cr+/qVE97CuJinFGK8gf2vtmtZA+5xC52Mmi9cSlvyZzSIHwxO0D8yZEYwgkTatADhwZtXlgGE9X1nqKwa4y04TNo+0m4x4Z3Xu/udA1vmJ0FOK09kx5yscM7/Pv/dogvf59O2u3NZXxxPXwxuVsrUPS9MLUfrTfDCkgBdySz0SmXJ5cDojv3ypcNbTGWMhlnJZ5TLElsyvqhe9UCMUzE7YdiCDOTcU7BtKFUVIYsza0fZKz1dtkaE77iiEZr5WYez6sRAhT9EeDhccYVyeh3Z/jNZNmv4T3JtGYCka+z54aoNPHZENEiqBltyNfVektPoYxQasJMc+/i5AHdjjKEtv006s5fFhqLj33m0j9a8XeByqElyLS/cdyZmLcqDovGEe6m+Yry0+C97bzjz30BufUjjjiUUdR0GyX9ocf2NmX0y4157bQ2yHyIZbJ3ktMHBGLt1gryubpwMY0iFDnqw0b/jE5H8uWEDA2XtmWCIr3mgNCycSUO/Zsr3LOw37+KR9edUi+Skc2aa4RAVOOqDN8CXd44KRobhd94SiHNnfc9exVmtCGCDs8A+HfqQStz0q/6/b5DZMVdvKJAj6c1D05v8GkUVEQlwF9pg+BIttXY7QxRo3HsuHaBk+5s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
